version: '3.7'

services:
  server:
    container_name: ${FILE_SERVER_HOST}
    build:
      context: ./server
    volumes:
      - servervol:/usr/app/serverdata
    expose:
      - 3000
    env_file:
      - .env
    command: python app.py ${FILE_SERVER_PORT}
    networks:
      - qalab1
  client:
    build:
      context: ./client
    container_name: client
    volumes:
      - clientvol:/usr/app/clientdata
    env_file:
      - .env
    ports:
      - 4000:4000
    command: python app.py ${FILE_SERVER_HOST} ${FILE_SERVER_PORT}
    depends_on:
      - server
    networks:
      - qalab1
networks:
  qalab1:
volumes:
  servervol:
  clientvol:
